






























#include <TypeIVRMLVelocity.h>
#include <TypeIVRMLDefinitions.h>
#include <TypeIVRMLMath.h>
#include <TypeIVRMLStep1Decisions.h>
#include <RMLVelocityInputParameters.h>
#include <RMLVelocityOutputParameters.h>
#include <RMLVector.h>
#include <ReflexxesAPI.h>
#include <RMLVelocityFlags.h>
#include <TypeIVRMLVelocityTools.h>
#include <math.h>
using namespace BkjIW;

void TypeIVRMLVelocity::nveH2(void){unsigned int i=(0x1bfd+1611-0x2248);double 
UlNR1=0.0,OFgA6=0.0,qI8hj=0.0,_DBry=0.0;for(i=(0xa14+3523-0x17d7);i<this->
NumberOfDOFs;i++){Polynomials[i].Ti1i1=(0x6e7+6202-0x1f21);if((this->CgOpp->
SelectionVector->VecData)[i]){OFgA6=(this->CgOpp->CurrentAccelerationVector->
VecData)[i];qI8hj=(this->CgOpp->CurrentVelocityVector->VecData)[i];_DBry=(this->
CgOpp->TargetVelocityVector->VecData)[i];(this->ExecutionTimes->VecData)[i]=0.0;
if(Pjr5p(OFgA6)){qI8hj=-qI8hj;OFgA6=-OFgA6;_DBry=-_DBry;}
if(et6lt(OFgA6,(this->CgOpp->MaxAccelerationVector->VecData)[i])){UlNR1=(OFgA6-(
this->CgOpp->MaxAccelerationVector->VecData)[i])/(this->CgOpp->MaxJerkVector->
VecData)[i];qI8hj+=0.5*UlNR1*(OFgA6-(this->CgOpp->MaxAccelerationVector->VecData
)[i])+UlNR1*(this->CgOpp->MaxAccelerationVector->VecData)[i];OFgA6=(this->CgOpp
->MaxAccelerationVector->VecData)[i];(this->ExecutionTimes->VecData)[i]+=UlNR1;}
if(JPylN(OFgA6,qI8hj,_DBry,(this->CgOpp->MaxJerkVector->VecData)[i])){
if(NPlTN(OFgA6,(this->CgOpp->MaxAccelerationVector->VecData)[i],qI8hj,_DBry,(
this->CgOpp->MaxJerkVector->VecData)[i])){(this->m7TST->VecData)[i]=wnb2g;(this
->ExecutionTimes->VecData)[i]+=e_az6(OFgA6,(this->CgOpp->MaxAccelerationVector->
VecData)[i],qI8hj,_DBry,(this->CgOpp->MaxJerkVector->VecData)[i]);}else{(this->
m7TST->VecData)[i]=YB481;(this->ExecutionTimes->VecData)[i]+=vwNO_(OFgA6,qI8hj,
_DBry,(this->CgOpp->MaxJerkVector->VecData)[i]);}}else{
if(KfGG_(OFgA6,(this->CgOpp->MaxAccelerationVector->VecData)[i],qI8hj,_DBry,(
this->CgOpp->MaxJerkVector->VecData)[i])){(this->m7TST->VecData)[i]=UoH_Q;(this
->ExecutionTimes->VecData)[i]+=upVNM(OFgA6,qI8hj,_DBry,(this->CgOpp->
MaxJerkVector->VecData)[i]);}else{(this->m7TST->VecData)[i]=YmqPd;(this->
ExecutionTimes->VecData)[i]+=Qfb2o(OFgA6,(this->CgOpp->MaxAccelerationVector->
VecData)[i],qI8hj,_DBry,(this->CgOpp->MaxJerkVector->VecData)[i]);}}}}return;}

void TypeIVRMLVelocity::Fvgfh(void){unsigned int i=(0x891+3122-0x14c3);double 
UlNR1=0.0,U2DcK=0.0,CYEL6=0.0;for(i=(0x679+6514-0x1feb);i<this->NumberOfDOFs;i++
){if((this->CgOpp->SelectionVector->VecData)[i]){(this->_aMjT->VecData)[i]=false
;(this->vUpOL->VecData)[i]=0.0;(this->Polynomials)[i].Ti1i1=(0xf1a+3910-0x1e60);
if(Pjr5p((this->CgOpp->CurrentAccelerationVector->VecData)[i])){(this->CgOpp->
CurrentPositionVector->VecData)[i]=-(this->CgOpp->CurrentPositionVector->VecData
)[i];(this->CgOpp->CurrentVelocityVector->VecData)[i]=-(this->CgOpp->
CurrentVelocityVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=-(this->CgOpp->CurrentAccelerationVector->VecData)[i];(this->CgOpp->
TargetVelocityVector->VecData)[i]=-(this->CgOpp->TargetVelocityVector->VecData)[
i];(this->_aMjT->VecData)[i]=!(this->_aMjT->VecData)[i];}
if(et6lt((this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->CgOpp->
MaxAccelerationVector->VecData)[i])){UlNR1=((this->CgOpp->
CurrentAccelerationVector->VecData)[i]-(this->CgOpp->MaxAccelerationVector->
VecData)[i])/(this->CgOpp->MaxJerkVector->VecData)[i];if((this->_aMjT->VecData)[
i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(
this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->CurrentAccelerationVector
->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->MaxJerkVector->VecData)[i]*0.5),
-(this->CgOpp->CurrentAccelerationVector->VecData)[i],-(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials
)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((((this->CgOpp->MaxJerkVector->
VecData)[i])/6.0),(-0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),-(
this->CgOpp->CurrentVelocityVector->VecData)[i],-(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->
Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->MaxJerkVector->VecData)[i],(this->CgOpp->CurrentAccelerationVector->VecData)[i
],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->Polynomials)[i]
.Ti1i1].TL5H9(0.0,(-(this->CgOpp->MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(
0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)
[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->CurrentPositionVector->VecData)[i]
+=UlNR1*(this->CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1)-_NEO8(UlNR1)*(this->CgOpp->
MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->CurrentVelocityVector->VecData)[i]
+=0.5*UlNR1*((this->CgOpp->CurrentAccelerationVector->VecData)[i]-(this->CgOpp->
MaxAccelerationVector->VecData)[i])+UlNR1*(this->CgOpp->MaxAccelerationVector->
VecData)[i];(this->CgOpp->CurrentAccelerationVector->VecData)[i]=(this->CgOpp->
MaxAccelerationVector->VecData)[i];(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;}if(((this->m7TST->VecData)[i]==UoH_Q)||((this->
m7TST->VecData)[i]==YmqPd)){UlNR1=(this->CgOpp->CurrentAccelerationVector->
VecData)[i]/(this->CgOpp->MaxJerkVector->VecData)[i];
if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i
].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((
this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)-_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*(this->CgOpp->
CurrentAccelerationVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=0.0;(this->vUpOL->VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[(
this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(this->Polynomials)[i].
Ti1i1++;(this->CgOpp->CurrentPositionVector->VecData)[i]=-(this->CgOpp->
CurrentPositionVector->VecData)[i];(this->CgOpp->CurrentVelocityVector->VecData)
[i]=-(this->CgOpp->CurrentVelocityVector->VecData)[i];(this->CgOpp->
CurrentAccelerationVector->VecData)[i]=-(this->CgOpp->CurrentAccelerationVector
->VecData)[i];(this->CgOpp->TargetVelocityVector->VecData)[i]=-(this->CgOpp->
TargetVelocityVector->VecData)[i];(this->_aMjT->VecData)[i]=!((this->_aMjT->
VecData)[i]);if((this->m7TST->VecData)[i]==UoH_Q){(this->m7TST->VecData)[i]=
YB481;}else{(this->m7TST->VecData)[i]=wnb2g;}}if((this->m7TST->VecData)[i]==
wnb2g){UlNR1=((this->CgOpp->MaxAccelerationVector->VecData)[i]-(this->CgOpp->
CurrentAccelerationVector->VecData)[i])/(this->CgOpp->MaxJerkVector->VecData)[i]
;if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[
i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp
->CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-
(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)+_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*((this->CgOpp->
MaxAccelerationVector->VecData)[i]-(this->CgOpp->CurrentAccelerationVector->
VecData)[i])+UlNR1*(this->CgOpp->CurrentAccelerationVector->VecData)[i];(this->
CgOpp->CurrentAccelerationVector->VecData)[i]=(this->CgOpp->
MaxAccelerationVector->VecData)[i];(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;
U2DcK=((this->CgOpp->TargetVelocityVector->VecData)[i]-(this->CgOpp->
CurrentVelocityVector->VecData)[i]-0.5*lJXU0((this->CgOpp->MaxAccelerationVector
->VecData)[i])/(this->CgOpp->MaxJerkVector->VecData)[i])/(this->CgOpp->
MaxAccelerationVector->VecData)[i];UlNR1=U2DcK;if((this->_aMjT->VecData)[i]){(
this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,-(
this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(
this->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->
CgOpp->CurrentAccelerationVector->VecData)[i],-(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials
)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,0.0,(this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->
vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,(this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->CgOpp
->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(0.5*(this->CgOpp
->CurrentAccelerationVector->VecData)[i]),(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}(this->CgOpp->CurrentPositionVector->VecData)[i]+=UlNR1*(this->
CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1);(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=(this->CgOpp->MaxAccelerationVector->VecData
)[i]*U2DcK;(this->CgOpp->CurrentAccelerationVector->VecData)[i]=(this->CgOpp->
MaxAccelerationVector->VecData)[i];(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;UlNR1=(this->CgOpp->CurrentAccelerationVector->
VecData)[i]/(this->CgOpp->MaxJerkVector->VecData)[i];
if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i
].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((
this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)-_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*(this->CgOpp->
CurrentAccelerationVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=0.0;(this->vUpOL->VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[(
this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(this->Polynomials)[i].
Ti1i1++;}else{

CYEL6=mdAxL(0.5*(lJXU0((this->CgOpp->CurrentAccelerationVector->VecData)[i])+2.0
*(this->CgOpp->MaxJerkVector->VecData)[i]*((this->CgOpp->TargetVelocityVector->
VecData)[i]-(this->CgOpp->CurrentVelocityVector->VecData)[i])));UlNR1=(CYEL6-(
this->CgOpp->CurrentAccelerationVector->VecData)[i])/(this->CgOpp->MaxJerkVector
->VecData)[i];if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],-
(this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);
(this->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->
CgOpp->MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector
->VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-
(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)+_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*(CYEL6-(this->CgOpp->
CurrentAccelerationVector->VecData)[i])+UlNR1*(this->CgOpp->
CurrentAccelerationVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=CYEL6;(this->vUpOL->VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[
(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(this->Polynomials)[i].
Ti1i1++;UlNR1=(this->CgOpp->CurrentAccelerationVector->VecData)[i]/(this->CgOpp
->MaxJerkVector->VecData)[i];
if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i
].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((
this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)-_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*(this->CgOpp->
CurrentAccelerationVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=0.0;(this->vUpOL->VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[(
this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(this->Polynomials)[i].
Ti1i1++;}(this->gSTLu->ExecutionTimes->VecData)[i]=(this->vUpOL->VecData)[i];if(
(this->_aMjT->VecData)[i]){(this->gSTLu->PositionValuesAtTargetVelocity->VecData
)[i]=-(this->CgOpp->CurrentPositionVector->VecData)[i];}else{(this->gSTLu->
PositionValuesAtTargetVelocity->VecData)[i]=(this->CgOpp->CurrentPositionVector
->VecData)[i];}if((this->vUpOL->VecData)[i]>this->SynchronizationTime){this->
gSTLu->DOFWithTheGreatestExecutionTime=i;this->SynchronizationTime=(this->vUpOL
->VecData)[i];}
UlNR1=kiQzO;if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,0.0,(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,-(this->
CgOpp->TargetVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->CurrentVelocityVector->VecData)[i],-(this->CgOpp->CurrentPositionVector->
VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this
->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,0.0,(this->vUpOL->VecData)[i]);(this
->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,(this->
CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)
[i],(this->vUpOL->VecData)[i]);}(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;
}else{(this->Polynomials)[i].Ti1i1=(0x1f09+691-0x21bc);}}return;}

void TypeIVRMLVelocity::VDr0j(void){unsigned int i=(0xdb5+5980-0x2511);double 
s8RNc=0.0,K80Yb=0.0,zVyfZ=0.0,oTcCZ=0.0,UlNR1=0.0,OFgA6=0.0,qI8hj=0.0,_DBry=0.0;
this->qYvqy();if(this->RijuD){this->RijuD=this->mhIY0();if((this->RijuD)&&(fabs(
(this->FiGD5->VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime])>UbufW)){
s8RNc=(this->CgOpp->MaxJerkVector->VecData)[this->gSTLu->
DOFWithTheGreatestExecutionTime]/fabs((this->FiGD5->VecData)[this->gSTLu->
DOFWithTheGreatestExecutionTime]);K80Yb=(this->CgOpp->MaxAccelerationVector->
VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime]/fabs((this->FiGD5->
VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime]);for(i=(0x764+1332-0xc98)
;i<this->NumberOfDOFs;i++){if((this->TC8_f->VecData)[i]){(this->ExecutionTimes->
VecData)[i]=0.0;(this->O99pp->VecData)[i]=fabs(s8RNc*(this->FiGD5->VecData)[i]);
if((this->O99pp->VecData)[i]<=0.0){(this->O99pp->VecData)[i]=CshoR;}(this->MGobU
->VecData)[i]=fabs(K80Yb*(this->FiGD5->VecData)[i]);if((this->MGobU->VecData)[i]
<=0.0){(this->MGobU->VecData)[i]=CshoR;}if(((this->O99pp->VecData)[i]>((this->
CgOpp->MaxJerkVector->VecData)[i]*(1.0+lpAYg)+UbufW))||((this->MGobU->VecData)[i
]>((this->CgOpp->MaxAccelerationVector->VecData)[i]*(1.0+lpAYg)+UbufW))){this->
RijuD=false;break;}}}}else{this->RijuD=false;}if(this->RijuD){for(i=
(0x1688+2143-0x1ee7);i<this->NumberOfDOFs;i++){this->ExecutionTimes->VecData[i]=
0.0;if((this->TC8_f->VecData)[i]){OFgA6=(this->CgOpp->CurrentAccelerationVector
->VecData)[i];qI8hj=(this->CgOpp->CurrentVelocityVector->VecData)[i];_DBry=(this
->CgOpp->TargetVelocityVector->VecData)[i];
if(Pjr5p(OFgA6)){qI8hj=-qI8hj;OFgA6=-OFgA6;_DBry=-_DBry;}
if(et6lt(OFgA6,(this->MGobU->VecData)[i])){UlNR1=(OFgA6-(this->MGobU->VecData)[i
])/(this->O99pp->VecData)[i];qI8hj+=0.5*UlNR1*(OFgA6-(this->MGobU->VecData)[i])+
UlNR1*(this->MGobU->VecData)[i];OFgA6=(this->MGobU->VecData)[i];(this->
ExecutionTimes->VecData)[i]+=UlNR1;}if((this->m7TST->VecData)[this->gSTLu->
DOFWithTheGreatestExecutionTime]==wnb2g){(this->ExecutionTimes->VecData)[i]+=
e_az6(OFgA6,(this->MGobU->VecData)[i],qI8hj,_DBry,(this->O99pp->VecData)[i]);}if
((this->m7TST->VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime]==YB481){(
this->ExecutionTimes->VecData)[i]+=vwNO_(OFgA6,qI8hj,_DBry,(this->O99pp->VecData
)[i]);}if((this->m7TST->VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime]==
YmqPd){(this->ExecutionTimes->VecData)[i]+=Qfb2o(OFgA6,(this->MGobU->VecData)[i]
,qI8hj,_DBry,(this->O99pp->VecData)[i]);}if((this->m7TST->VecData)[this->gSTLu->
DOFWithTheGreatestExecutionTime]==UoH_Q){(this->ExecutionTimes->VecData)[i]+=
upVNM(OFgA6,qI8hj,_DBry,(this->O99pp->VecData)[i]);}}}zVyfZ=0.0;oTcCZ=0.0;for(i=
(0x10b5+646-0x133b);i<this->NumberOfDOFs;i++){if((this->TC8_f->VecData)[i]){
zVyfZ+=(this->ExecutionTimes->VecData)[i];oTcCZ+=1.0;}}if(oTcCZ>0.0){zVyfZ/=
oTcCZ;for(i=(0x1ed3+588-0x211f);i<this->NumberOfDOFs;i++){if((this->TC8_f->
VecData)[i]){if(fabs((this->ExecutionTimes->VecData)[i]-zVyfZ)>(UbufW+lpAYg*
zVyfZ)){this->RijuD=false;break;}}}}}}if(this->RijuD){for(i=(0xdb8+4531-0x1f6b);
i<this->NumberOfDOFs;i++){if((this->TC8_f->VecData)[i]){(this->CgOpp->
MaxAccelerationVector->VecData)[i]=(this->MGobU->VecData)[i];(this->CgOpp->
MaxJerkVector->VecData)[i]=(this->O99pp->VecData)[i];(this->m7TST->VecData)[i]=(
this->m7TST->VecData)[this->gSTLu->DOFWithTheGreatestExecutionTime];}}}return;}

int TypeIVRMLVelocity::A04l_(const double&jhvDE,const double&OverrideValue,
RMLVelocityOutputParameters*a77oB)const{unsigned int i=(0x1459+3850-0x2363);int 
p_kSI=ReflexxesAPI::RML_FINAL_STATE_REACHED,j=(0x171a+3532-0x24e6),m85bi=
(0x247+3039-0xe26);
for(i=(0x3bb+3872-0x12db);i<this->NumberOfDOFs;i++){if((this->CgOpp->
SelectionVector->VecData)[i]){j=(0x1c39+1065-0x2062);while((jhvDE>(((this->
Polynomials)[i].So6Nc)[j]))&&(j<bfmk1)){j++;}(a77oB->NewPositionVector->VecData)
[i]=(this->Polynomials)[i].ZMssN[j].cPb5F(jhvDE);(a77oB->NewVelocityVector->
VecData)[i]=(this->Polynomials)[i].YWp8I[j].cPb5F(jhvDE)*OverrideValue;(a77oB->
NewAccelerationVector->VecData)[i]=(this->Polynomials)[i].sabLl[j].cPb5F(jhvDE)*
lJXU0(OverrideValue);if(j<((this->Polynomials)[i].Ti1i1)-(0x111b+3914-0x2064)){
p_kSI=ReflexxesAPI::RML_WORKING;}(a77oB->PositionValuesAtTargetVelocity->VecData
)[i]=(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1-
(0x11c5+352-0x1324)]._Bp69;a77oB->Polynomials->NumberOfCurrentlyValidSegments[i]
=(this->Polynomials)[i].Ti1i1-j;for(m85bi=(0x99a+5362-0x1e8c);m85bi<a77oB->
Polynomials->NumberOfCurrentlyValidSegments[i];m85bi++){a77oB->Polynomials->
Coefficients[i][m85bi].Time_ValidUntil=(this->Polynomials)[i].So6Nc[j+m85bi]-(
this->MKEeV-this->CycleTime);a77oB->Polynomials->Coefficients[i][m85bi].
AccelerationPolynomialCoefficients[(0x102a+3226-0x1cc4)]=(this->Polynomials)[i].
sabLl[j+m85bi]._Bp69-(this->Polynomials)[i].sabLl[j+m85bi].yTfgT*(this->
Polynomials)[i].sabLl[j+m85bi].Mlr3t;a77oB->Polynomials->Coefficients[i][m85bi].
AccelerationPolynomialCoefficients[(0x85a+6802-0x22eb)]=(this->Polynomials)[i].
sabLl[j+m85bi].yTfgT;a77oB->Polynomials->Coefficients[i][m85bi].
VelocityPolynomialCoefficients[(0x33+8706-0x2235)]=(this->Polynomials)[i].YWp8I[
j+m85bi]._Bp69+(this->Polynomials)[i].YWp8I[j+m85bi].Mlr3t*((this->Polynomials)[
i].YWp8I[j+m85bi].PG51e*(this->Polynomials)[i].YWp8I[j+m85bi].Mlr3t-(this->
Polynomials)[i].YWp8I[j+m85bi].yTfgT);a77oB->Polynomials->Coefficients[i][m85bi]
.VelocityPolynomialCoefficients[(0x1239+3469-0x1fc5)]=(this->Polynomials)[i].
YWp8I[j+m85bi].yTfgT-2.0*(this->Polynomials)[i].YWp8I[j+m85bi].PG51e*(this->
Polynomials)[i].YWp8I[j+m85bi].Mlr3t;a77oB->Polynomials->Coefficients[i][m85bi].
VelocityPolynomialCoefficients[(0x203+1918-0x97f)]=(this->Polynomials)[i].YWp8I[
j+m85bi].PG51e;a77oB->Polynomials->Coefficients[i][m85bi].
PositionPolynomialCoefficients[(0x33a+2244-0xbfe)]=(this->Polynomials)[i].ZMssN[
j+m85bi]._Bp69+(this->Polynomials)[i].ZMssN[j+m85bi].Mlr3t*((this->Polynomials)[
i].ZMssN[j+m85bi].Mlr3t*((this->Polynomials)[i].ZMssN[j+m85bi].PG51e-(this->
Polynomials)[i].ZMssN[j+m85bi].Mlr3t*(this->Polynomials)[i].ZMssN[j+m85bi].FTf8f
)-(this->Polynomials)[i].ZMssN[j+m85bi].yTfgT);a77oB->Polynomials->Coefficients[
i][m85bi].PositionPolynomialCoefficients[(0xee3+4960-0x2242)]=(this->Polynomials
)[i].ZMssN[j+m85bi].yTfgT+(this->Polynomials)[i].ZMssN[j+m85bi].Mlr3t*(3.0*(this
->Polynomials)[i].ZMssN[j+m85bi].FTf8f*(this->Polynomials)[i].ZMssN[j+m85bi].
Mlr3t-2.0*(this->Polynomials)[i].ZMssN[j+m85bi].PG51e);a77oB->Polynomials->
Coefficients[i][m85bi].PositionPolynomialCoefficients[(0x9b9+7042-0x2539)]=(this
->Polynomials)[i].ZMssN[j+m85bi].PG51e-3.0*(this->Polynomials)[i].ZMssN[j+m85bi]
.FTf8f*(this->Polynomials)[i].ZMssN[j+m85bi].Mlr3t;a77oB->Polynomials->
Coefficients[i][m85bi].PositionPolynomialCoefficients[(0x7d+253-0x177)]=(this->
Polynomials)[i].ZMssN[j+m85bi].FTf8f;}}else{(a77oB->NewPositionVector->VecData)[
i]=(this->CgOpp->CurrentPositionVector->VecData)[i];(a77oB->NewVelocityVector->
VecData)[i]=(this->CgOpp->CurrentVelocityVector->VecData)[i];(a77oB->
NewAccelerationVector->VecData)[i]=(this->CgOpp->CurrentAccelerationVector->
VecData)[i];(a77oB->PositionValuesAtTargetVelocity->VecData)[i]=(this->CgOpp->
CurrentPositionVector->VecData)[i];a77oB->Polynomials->
NumberOfCurrentlyValidSegments[i]=(0xcaf+1341-0x11ec);}}return(p_kSI);}

void TypeIVRMLVelocity::ar_Rj(void){unsigned int i=(0x199d+812-0x1cc9);double 
UlNR1=0.0,YlsMh=0.0,i_Y56=0.0,kJRdm=0.0,B8jft=0.0;for(i=(0x75b+3088-0x136b);i<
this->NumberOfDOFs;i++){if((this->CgOpp->SelectionVector->VecData)[i]){(this->
_aMjT->VecData)[i]=false;(this->vUpOL->VecData)[i]=0.0;(this->Polynomials)[i].
Ti1i1=(0x1c99+1076-0x20cd);
if(Pjr5p((this->CgOpp->CurrentAccelerationVector->VecData)[i])){(this->CgOpp->
CurrentPositionVector->VecData)[i]=-(this->CgOpp->CurrentPositionVector->VecData
)[i];(this->CgOpp->CurrentVelocityVector->VecData)[i]=-(this->CgOpp->
CurrentVelocityVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=-(this->CgOpp->CurrentAccelerationVector->VecData)[i];(this->CgOpp->
TargetVelocityVector->VecData)[i]=-(this->CgOpp->TargetVelocityVector->VecData)[
i];(this->_aMjT->VecData)[i]=!(this->_aMjT->VecData)[i];}
if(et6lt((this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->CgOpp->
MaxAccelerationVector->VecData)[i])){UlNR1=((this->CgOpp->
CurrentAccelerationVector->VecData)[i]-(this->CgOpp->MaxAccelerationVector->
VecData)[i])/(this->CgOpp->MaxJerkVector->VecData)[i];if((this->_aMjT->VecData)[
i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(
this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->CurrentAccelerationVector
->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->MaxJerkVector->VecData)[i]*0.5),
-(this->CgOpp->CurrentAccelerationVector->VecData)[i],-(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials
)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((((this->CgOpp->MaxJerkVector->
VecData)[i])/6.0),(-0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),-(
this->CgOpp->CurrentVelocityVector->VecData)[i],-(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->
Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->MaxJerkVector->VecData)[i],(this->CgOpp->CurrentAccelerationVector->VecData)[i
],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->Polynomials)[i]
.Ti1i1].TL5H9(0.0,(-(this->CgOpp->MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(
0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)
[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->CurrentPositionVector->VecData)[i]
+=UlNR1*(this->CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1)-_NEO8(UlNR1)*(this->CgOpp->
MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->CurrentVelocityVector->VecData)[i]
+=0.5*UlNR1*((this->CgOpp->CurrentAccelerationVector->VecData)[i]-(this->CgOpp->
MaxAccelerationVector->VecData)[i])+UlNR1*(this->CgOpp->MaxAccelerationVector->
VecData)[i];(this->CgOpp->CurrentAccelerationVector->VecData)[i]=(this->CgOpp->
MaxAccelerationVector->VecData)[i];(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;}
if(!JPylN((this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->TargetVelocityVector->VecData)[
i],(this->CgOpp->MaxJerkVector->VecData)[i])){UlNR1=(this->CgOpp->
CurrentAccelerationVector->VecData)[i]/(this->CgOpp->MaxJerkVector->VecData)[i];
if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i
].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((
this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
)-_NEO8(UlNR1)*(this->CgOpp->MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->
CurrentVelocityVector->VecData)[i]+=0.5*UlNR1*(this->CgOpp->
CurrentAccelerationVector->VecData)[i];(this->CgOpp->CurrentAccelerationVector->
VecData)[i]=0.0;(this->vUpOL->VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[(
this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(this->Polynomials)[i].
Ti1i1++;(this->CgOpp->CurrentPositionVector->VecData)[i]=-(this->CgOpp->
CurrentPositionVector->VecData)[i];(this->CgOpp->CurrentVelocityVector->VecData)
[i]=-(this->CgOpp->CurrentVelocityVector->VecData)[i];(this->CgOpp->
CurrentAccelerationVector->VecData)[i]=-(this->CgOpp->CurrentAccelerationVector
->VecData)[i];(this->CgOpp->TargetVelocityVector->VecData)[i]=-(this->CgOpp->
TargetVelocityVector->VecData)[i];(this->_aMjT->VecData)[i]=!((this->_aMjT->
VecData)[i]);}
if(Lerqv((this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->TargetVelocityVector->VecData)[
i],(this->CgOpp->MaxJerkVector->VecData)[i],(this->vUpOL->VecData)[i],this->
SynchronizationTime)){
B8jft=(2.0*this->CgOpp->MaxJerkVector->VecData[i]*(SynchronizationTime-(this->
vUpOL->VecData)[i])-2.0*this->CgOpp->CurrentAccelerationVector->VecData[i]);if(
B8jft==0.0){YlsMh=this->CgOpp->CurrentAccelerationVector->VecData[i];i_Y56=(this
->vUpOL->VecData)[i];kJRdm=(this->vUpOL->VecData)[i];}else{YlsMh=(2.0*this->
CgOpp->MaxJerkVector->VecData[i]*(this->CgOpp->TargetVelocityVector->VecData[i]-
this->CgOpp->CurrentVelocityVector->VecData[i])-lJXU0(this->CgOpp->
CurrentAccelerationVector->VecData[i]))/B8jft;if(YlsMh>this->CgOpp->
CurrentAccelerationVector->VecData[i]){YlsMh=this->CgOpp->
CurrentAccelerationVector->VecData[i];}if(YlsMh<0.0){YlsMh=0.0;}i_Y56=(this->
vUpOL->VecData)[i]+(this->CgOpp->CurrentAccelerationVector->VecData[i]-YlsMh)/
this->CgOpp->MaxJerkVector->VecData[i];if(i_Y56<(this->vUpOL->VecData)[i]){i_Y56
=(this->vUpOL->VecData)[i];}kJRdm=SynchronizationTime-YlsMh/this->CgOpp->
MaxJerkVector->VecData[i];if(kJRdm<i_Y56){kJRdm=i_Y56;}}
UlNR1=i_Y56-(this->vUpOL->VecData)[i];if((this->_aMjT->VecData)[i]){(this->
Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->
MaxJerkVector->VecData)[i],-(this->CgOpp->CurrentAccelerationVector->VecData)[i]
,(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->Polynomials)[i].
Ti1i1].TL5H9(0.0,((this->CgOpp->MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],-(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9(((this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-
0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->
CurrentVelocityVector->VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData
)[i],(this->vUpOL->VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],(
this->CgOpp->CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(
this->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->
CgOpp->MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->
VecData)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-
(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}(this->CgOpp->CurrentPositionVector->VecData)[i]+=UlNR1*(this->
CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1)-_NEO8(UlNR1)*(this->CgOpp->
MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->CurrentVelocityVector->VecData)[i]
+=0.5*UlNR1*((this->CgOpp->CurrentAccelerationVector->VecData)[i]-YlsMh)+UlNR1*
YlsMh;(this->CgOpp->CurrentAccelerationVector->VecData)[i]=YlsMh;(this->vUpOL->
VecData)[i]+=UlNR1;(this->Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(
this->vUpOL->VecData)[i];(this->Polynomials)[i].Ti1i1++;}else{
YlsMh=0.5*(this->CgOpp->MaxJerkVector->VecData[i]*(this->SynchronizationTime-(
this->vUpOL->VecData)[i])+this->CgOpp->CurrentAccelerationVector->VecData[i])-
0.5*BkjIW::mdAxL(4.0*this->CgOpp->MaxJerkVector->VecData[i]*(this->CgOpp->
CurrentVelocityVector->VecData[i]-this->CgOpp->TargetVelocityVector->VecData[i])
+this->CgOpp->MaxJerkVector->VecData[i]*(this->SynchronizationTime-(this->vUpOL
->VecData)[i])*(this->CgOpp->MaxJerkVector->VecData[i]*(this->
SynchronizationTime-(this->vUpOL->VecData)[i])+2.0*this->CgOpp->
CurrentAccelerationVector->VecData[i])-lJXU0(this->CgOpp->
CurrentAccelerationVector->VecData[i]));if(YlsMh<this->CgOpp->
CurrentAccelerationVector->VecData[i]){YlsMh=this->CgOpp->
CurrentAccelerationVector->VecData[i];}i_Y56=(this->vUpOL->VecData)[i]+(YlsMh-
this->CgOpp->CurrentAccelerationVector->VecData[i])/this->CgOpp->MaxJerkVector->
VecData[i];if(i_Y56<(this->vUpOL->VecData)[i]){i_Y56=(this->vUpOL->VecData)[i];}
kJRdm=this->SynchronizationTime-YlsMh/this->CgOpp->MaxJerkVector->VecData[i];if(
kJRdm<i_Y56){kJRdm=i_Y56;}
if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i
].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,(-(this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),-(this->CgOpp->CurrentAccelerationVector->
VecData)[i],-(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->
VecData)[i]);(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9((-
(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(-0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]),-(this->CgOpp->CurrentVelocityVector->
VecData)[i],-(this->CgOpp->CurrentPositionVector->VecData)[i],(this->vUpOL->
VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].
TL5H9(0.0,0.0,(this->CgOpp->MaxJerkVector->VecData)[i],(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->
MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->CurrentAccelerationVector->VecData
)[i],(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i])
;(this->Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((this->CgOpp
->MaxJerkVector->VecData)[i]/6.0),(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}UlNR1=i_Y56-(this
->vUpOL->VecData)[i];(this->CgOpp->CurrentPositionVector->VecData)[i]+=UlNR1*(
this->CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1)+_NEO8(UlNR1)*(this->CgOpp->
MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->CurrentVelocityVector->VecData)[i]
+=0.5*UlNR1*(YlsMh-(this->CgOpp->CurrentAccelerationVector->VecData)[i])+UlNR1*(
this->CgOpp->CurrentAccelerationVector->VecData)[i];(this->CgOpp->
CurrentAccelerationVector->VecData)[i]=YlsMh;(this->vUpOL->VecData)[i]+=UlNR1;(
this->Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)
[i];(this->Polynomials)[i].Ti1i1++;}
UlNR1=kJRdm-i_Y56;if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(
this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,-(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->CurrentAccelerationVector->VecData)[i],-(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,(-0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),-(this->CgOpp->CurrentVelocityVector->VecData)[i],-(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->
Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,(this->
CgOpp->CurrentAccelerationVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,(0.5*(this->CgOpp->CurrentAccelerationVector->
VecData)[i]),(this->CgOpp->CurrentVelocityVector->VecData)[i],(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->
CurrentPositionVector->VecData)[i]+=UlNR1*(this->CgOpp->CurrentVelocityVector->
VecData)[i]+0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1
);(this->CgOpp->CurrentVelocityVector->VecData)[i]+=YlsMh*UlNR1;(this->CgOpp->
CurrentAccelerationVector->VecData)[i]=YlsMh;(this->vUpOL->VecData)[i]+=UlNR1;(
this->Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)
[i];(this->Polynomials)[i].Ti1i1++;
UlNR1=YlsMh/(this->CgOpp->MaxJerkVector->VecData)[i];if((this->_aMjT->VecData)[i
]){(this->Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(
this->CgOpp->MaxJerkVector->VecData)[i],-(this->CgOpp->CurrentAccelerationVector
->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,((this->CgOpp->MaxJerkVector->VecData)[i]*0.5),
-(this->CgOpp->CurrentAccelerationVector->VecData)[i],-(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials
)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(((this->CgOpp->MaxJerkVector->
VecData)[i]/6.0),(-0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),-(
this->CgOpp->CurrentVelocityVector->VecData)[i],-(this->CgOpp->
CurrentPositionVector->VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->
Polynomials)[i].sabLl[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->MaxJerkVector->VecData)[i],(this->CgOpp->CurrentAccelerationVector->VecData)[i
],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].YWp8I[(this->Polynomials)[i]
.Ti1i1].TL5H9(0.0,(-(this->CgOpp->MaxJerkVector->VecData)[i]*0.5),(this->CgOpp->
CurrentAccelerationVector->VecData)[i],(this->CgOpp->CurrentVelocityVector->
VecData)[i],(this->vUpOL->VecData)[i]);(this->Polynomials)[i].ZMssN[(this->
Polynomials)[i].Ti1i1].TL5H9((-(this->CgOpp->MaxJerkVector->VecData)[i]/6.0),(
0.5*(this->CgOpp->CurrentAccelerationVector->VecData)[i]),(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)
[i],(this->vUpOL->VecData)[i]);}(this->CgOpp->CurrentPositionVector->VecData)[i]
+=UlNR1*(this->CgOpp->CurrentVelocityVector->VecData)[i]+0.5*(this->CgOpp->
CurrentAccelerationVector->VecData)[i]*lJXU0(UlNR1)-_NEO8(UlNR1)*(this->CgOpp->
MaxJerkVector->VecData)[i]/6.0;(this->CgOpp->CurrentVelocityVector->VecData)[i]
+=0.5*UlNR1*(this->CgOpp->CurrentAccelerationVector->VecData)[i];(this->CgOpp->
CurrentAccelerationVector->VecData)[i]=0.0;(this->vUpOL->VecData)[i]+=UlNR1;(
this->Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)
[i];(this->Polynomials)[i].Ti1i1++;
UlNR1=kiQzO;if((this->_aMjT->VecData)[i]){(this->Polynomials)[i].sabLl[(this->
Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,0.0,(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,-(this->
CgOpp->TargetVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,-(this->CgOpp
->CurrentVelocityVector->VecData)[i],-(this->CgOpp->CurrentPositionVector->
VecData)[i],(this->vUpOL->VecData)[i]);}else{(this->Polynomials)[i].sabLl[(this
->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,0.0,(this->vUpOL->VecData)[i]);(this
->Polynomials)[i].YWp8I[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,0.0,(this->
CgOpp->CurrentVelocityVector->VecData)[i],(this->vUpOL->VecData)[i]);(this->
Polynomials)[i].ZMssN[(this->Polynomials)[i].Ti1i1].TL5H9(0.0,0.0,(this->CgOpp->
CurrentVelocityVector->VecData)[i],(this->CgOpp->CurrentPositionVector->VecData)
[i],(this->vUpOL->VecData)[i]);}(this->vUpOL->VecData)[i]+=UlNR1;(this->
Polynomials)[i].So6Nc[(this->Polynomials)[i].Ti1i1]=(this->vUpOL->VecData)[i];(
this->Polynomials)[i].Ti1i1++;
}else{(this->Polynomials)[i].Ti1i1=(0x17d2+2548-0x21c6);}}return;}
